import "../core/deep_copy.dart";
import "../core/platforms.dart";
import "../core/server_config.dart";
import "../core/validators.dart";
import "prompt.dart";

class WizardResult {
  WizardResult({required this.config, required this.platforms});

  final Map<String, dynamic> config;
  final List<String> platforms;
}

class Wizard {
  Wizard({required this.prompt});

  final Prompt prompt;

  WizardResult run(ServerConfig server, {required String defaultPlatformsRaw}) {
    final cfg = deepCopyMap(server.defaultConfig);

    final platformsRaw = prompt.askText(
      label: "Platforms (comma separated)",
      defaultValue: defaultPlatformsRaw,
      validate: (v) {
        try {
          parsePlatforms(v);
          return true;
        } catch (_) {
          return false;
        }
      },
      invalidMessage: "Supported: android, ios, web, macos, windows, linux",
    );
    final platforms = parsePlatforms(platformsRaw);

    final appName = prompt.askText(
      label: "App name (snake_case)",
      defaultValue: (cfg["appName"] as String?) ?? "flutter_starter",
      validate: isValidAppName,
      invalidMessage:
          "Must be lowercase snake_case, start with a letter, and contain only letters/numbers/underscore.",
    );
    cfg["appName"] = appName;

    final suggested = derivePackageId(appName);
    final packageId = prompt.askText(
      label: "Package id",
      defaultValue: (cfg["packageId"] as String?) ?? suggested,
      validate: isValidPackageId,
      invalidMessage: "Must look like com.example.app_name",
    );
    cfg["packageId"] = packageId;

    final description = prompt.askText(
      label: "Description",
      defaultValue: (cfg["description"] as String?) ??
          "Production-ready Flutter scaffold generated by FlutterInit.",
      validate: (v) => v.trim().isNotEmpty,
      invalidMessage: "Description cannot be empty.",
    );
    cfg["description"] = description;

    final theme = (cfg["theme"] as Map).cast<String, dynamic>();
    final themePresetOptions =
        _choicesFromOptions(server.options["themePresetOptions"]);
    theme["preset"] = prompt.askChoice(
      label: "Theme preset",
      choices: themePresetOptions,
      defaultValue: theme["preset"] as String? ?? "material3",
    );
    theme["primaryColor"] = prompt.askText(
      label: "Primary color (hex)",
      defaultValue: (theme["primaryColor"] as String?) ?? "#6750A4",
      validate: (v) =>
          RegExp(r"^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$").hasMatch(v),
      invalidMessage: "Expected hex like #6750A4 or #FF6750A4",
    );
    final darkMode = (theme["darkMode"] as Map).cast<String, dynamic>();
    darkMode["enabled"] = prompt.askBool(
        label: "Enable dark mode",
        defaultValue: darkMode["enabled"] as bool? ?? true);
    darkMode["system"] = prompt.askBool(
        label: "Follow system theme",
        defaultValue: darkMode["system"] as bool? ?? true);
    theme["darkMode"] = darkMode;
    cfg["theme"] = theme;

    final icons = (cfg["icons"] as Map).cast<String, dynamic>();
    icons["iconsax_plus"] = prompt.askBool(
        label: "Include iconsax_plus",
        defaultValue: icons["iconsax_plus"] as bool? ?? false);
    icons["flutter_remix"] = prompt.askBool(
        label: "Include flutter_remix",
        defaultValue: icons["flutter_remix"] as bool? ?? false);
    icons["hugeicons"] = prompt.askBool(
        label: "Include hugeicons",
        defaultValue: icons["hugeicons"] as bool? ?? false);
    cfg["icons"] = icons;

    final architectureOptions =
        _choicesFromOptions(server.options["architectureOptions"]);
    cfg["architecture"] = prompt.askChoice(
      label: "Architecture",
      choices: architectureOptions,
      defaultValue: cfg["architecture"] as String? ?? "feature-first",
    );

    final stateOptions =
        _choicesFromOptions(server.options["stateManagementOptions"]);
    cfg["stateManagement"] = prompt.askChoice(
      label: "State management",
      choices: stateOptions,
      defaultValue: cfg["stateManagement"] as String? ?? "riverpod",
    );

    final navOptions = _choicesFromOptions(server.options["navigationOptions"]);
    cfg["navigation"] = prompt.askChoice(
      label: "Navigation",
      choices: navOptions,
      defaultValue: cfg["navigation"] as String? ?? "go_router",
    );

    final backendOptions =
        _choicesFromOptions(server.options["backendOptions"]);
    final backendProvider = prompt.askChoice(
      label: "Backend provider",
      choices: backendOptions,
      defaultValue:
          ((cfg["backend"] as Map?)?["provider"] as String?) ?? "none",
    );

    cfg["backend"] =
        _buildBackend(cfg["backend"] as Map<String, dynamic>?, backendProvider);

    final localization = (cfg["localization"] as Map).cast<String, dynamic>();
    localization["enabled"] = prompt.askBool(
        label: "Enable localization",
        defaultValue: localization["enabled"] as bool? ?? true);
    if (localization["enabled"] == true) {
      final localesRaw = prompt.askText(
        label: "Supported locales (comma separated)",
        defaultValue: ((localization["supportedLocales"] as List?)
                ?.whereType<String>()
                .join(",")) ??
            "en,es",
        validate: (v) => v
            .split(",")
            .map((s) => s.trim())
            .where((s) => s.isNotEmpty)
            .isNotEmpty,
      );
      localization["supportedLocales"] = localesRaw
          .split(",")
          .map((s) => s.trim())
          .where((s) => s.isNotEmpty)
          .toList();
    }
    cfg["localization"] = localization;

    cfg["misc"] = _buildMisc(
        (cfg["misc"] as Map).cast<String, dynamic>(), backendProvider);
    return WizardResult(config: cfg, platforms: platforms);
  }

  Map<String, dynamic> _buildBackend(
      Map<String, dynamic>? existing, String provider) {
    final backend = existing ?? <String, dynamic>{};
    backend["provider"] = provider;
    if (provider == "none") {
      backend.remove("options");
      return backend;
    }

    final options = (backend["options"] as Map?)?.cast<String, dynamic>() ??
        <String, dynamic>{};
    switch (provider) {
      case "firebase":
        options["authEmail"] = prompt.askBool(
            label: "Firebase: Email auth",
            defaultValue: options["authEmail"] as bool? ?? true);
        options["authGoogle"] = prompt.askBool(
            label: "Firebase: Google auth",
            defaultValue: options["authGoogle"] as bool? ?? true);
        options["authPhone"] = prompt.askBool(
            label: "Firebase: Phone auth",
            defaultValue: options["authPhone"] as bool? ?? false);
        options["firestore"] = prompt.askBool(
            label: "Firebase: Firestore",
            defaultValue: options["firestore"] as bool? ?? true);
        options["realtimeDb"] = prompt.askBool(
            label: "Firebase: Realtime DB",
            defaultValue: options["realtimeDb"] as bool? ?? false);
        options["storage"] = prompt.askBool(
            label: "Firebase: Storage",
            defaultValue: options["storage"] as bool? ?? true);
        options["analytics"] = prompt.askBool(
            label: "Firebase: Analytics",
            defaultValue: options["analytics"] as bool? ?? true);
        options["crashlytics"] = prompt.askBool(
            label: "Firebase: Crashlytics",
            defaultValue: options["crashlytics"] as bool? ?? true);
        break;
      case "supabase":
        options["auth"] = prompt.askBool(
            label: "Supabase: Auth",
            defaultValue: options["auth"] as bool? ?? true);
        options["database"] = prompt.askBool(
            label: "Supabase: Database",
            defaultValue: options["database"] as bool? ?? true);
        options["edgeFunctions"] = prompt.askBool(
            label: "Supabase: Edge functions",
            defaultValue: options["edgeFunctions"] as bool? ?? true);
        break;
      case "appwrite":
        options["auth"] = prompt.askBool(
            label: "Appwrite: Auth",
            defaultValue: options["auth"] as bool? ?? true);
        options["database"] = prompt.askBool(
            label: "Appwrite: Database",
            defaultValue: options["database"] as bool? ?? true);
        options["storage"] = prompt.askBool(
            label: "Appwrite: Storage",
            defaultValue: options["storage"] as bool? ?? true);
        break;
      case "custom":
        options["baseUrl"] = prompt.askText(
            label: "Custom backend base URL (optional)",
            defaultValue: options["baseUrl"] as String? ?? "");
        break;
    }
    backend["options"] = options;
    return backend;
  }

  Map<String, dynamic> _buildMisc(
      Map<String, dynamic> misc, String backendProvider) {
    misc["usesScreenutil"] = prompt.askBool(
        label: "Use ScreenUtil",
        defaultValue: misc["usesScreenutil"] as bool? ?? true);
    misc["usesFlutterNativeSplash"] = prompt.askBool(
        label: "Use flutter_native_splash",
        defaultValue: misc["usesFlutterNativeSplash"] as bool? ?? true);
    misc["usesFlutterSvg"] = prompt.askBool(
        label: "Use flutter_svg",
        defaultValue: misc["usesFlutterSvg"] as bool? ?? true);
    misc["usesSkeletonizer"] = prompt.askBool(
        label: "Use skeletonizer",
        defaultValue: misc["usesSkeletonizer"] as bool? ?? true);
    misc["usesLogger"] = prompt.askBool(
        label: "Use logger", defaultValue: misc["usesLogger"] as bool? ?? true);
    misc["usesDotenv"] = prompt.askBool(
        label: "Use flutter_dotenv",
        defaultValue: misc["usesDotenv"] as bool? ?? true);
    misc["usesCachedNetworkImage"] = prompt.askBool(
        label: "Use cached_network_image",
        defaultValue: misc["usesCachedNetworkImage"] as bool? ?? true);

    final usesDio = prompt.askBool(
        label: "Use Dio", defaultValue: misc["usesDio"] as bool? ?? false);
    misc["usesDio"] = usesDio;
    misc["usesHttp"] = usesDio
        ? false
        : prompt.askBool(
            label: "Use HTTP client",
            defaultValue: misc["usesHttp"] as bool? ?? false);

    misc["usesSecureStorage"] = prompt.askBool(
        label: "Use flutter_secure_storage",
        defaultValue: misc["usesSecureStorage"] as bool? ?? true);
    misc["usesSharedPreferences"] = prompt.askBool(
        label: "Use shared_preferences",
        defaultValue: misc["usesSharedPreferences"] as bool? ?? true);
    misc["usesHive"] = prompt.askBool(
        label: "Use hive", defaultValue: misc["usesHive"] as bool? ?? false);

    misc["usesUrlLauncher"] = prompt.askBool(
        label: "Use url_launcher",
        defaultValue: misc["usesUrlLauncher"] as bool? ?? true);
    misc["usesPathProvider"] = prompt.askBool(
        label: "Use path_provider",
        defaultValue: misc["usesPathProvider"] as bool? ?? true);
    misc["usesSharePlus"] = prompt.askBool(
        label: "Use share_plus",
        defaultValue: misc["usesSharePlus"] as bool? ?? false);
    misc["usesPermissionHandler"] = prompt.askBool(
        label: "Use permission_handler",
        defaultValue: misc["usesPermissionHandler"] as bool? ?? true);

    misc["usesDeviceInfoPlus"] = prompt.askBool(
        label: "Use device_info_plus",
        defaultValue: misc["usesDeviceInfoPlus"] as bool? ?? true);
    misc["usesAppVersionUpdate"] = prompt.askBool(
        label: "Use app_version_update",
        defaultValue: misc["usesAppVersionUpdate"] as bool? ?? true);
    misc["usesGeolocator"] = prompt.askBool(
        label: "Use geolocator",
        defaultValue: misc["usesGeolocator"] as bool? ?? false);

    misc["usesFlutterHooks"] = prompt.askBool(
        label: "Use flutter_hooks",
        defaultValue: misc["usesFlutterHooks"] as bool? ?? false);
    misc["usesImagePicker"] = prompt.askBool(
        label: "Use image_picker",
        defaultValue: misc["usesImagePicker"] as bool? ?? false);
    misc["usesFilePicker"] = prompt.askBool(
        label: "Use file_picker",
        defaultValue: misc["usesFilePicker"] as bool? ?? false);

    if (backendProvider == "custom" &&
        !(misc["usesDio"] == true || misc["usesHttp"] == true)) {
      misc["usesDio"] = true;
      misc["usesHttp"] = false;
    }

    return misc;
  }

  List<Choice> _choicesFromOptions(dynamic optionsRaw) {
    if (optionsRaw is! List) return const [];
    final out = <Choice>[];
    for (final entry in optionsRaw) {
      if (entry is Map) {
        final value = entry["value"];
        final label = entry["label"];
        if (value is String && label is String) {
          out.add(Choice(value: value, label: label));
        }
      }
    }
    return out;
  }
}
